name: Lint et Tests sur Fusion vers Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Installer pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "8"

      - name: Installer les dépendances
        run: pnpm install

      - name: Exécuter le linting
        run: pnpm run lint

      - name: Exécuter les tests
        run: pnpm run test
