name: Lint, Tests et Déploiement sur Vercel

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installer pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "8"

      - name: Installer les dépendances
        run: pnpm install

      - name: Exécuter le linting
        run: pnpm run lint

      - name: Exécuter les tests
        run: pnpm run test

  deploy:
    needs: lint_and_test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - uses: actions/checkout@v4

      - name: Installer Vercel CLI
        run: npm install --global vercel@latest

      - name: Déployer sur Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
